[package]
name = "rust_proj"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.29.0"
libc = "^0.2"
sysinfo = "0.21.0"
clap = { version = "4.3.17", features = ["derive"] }
assert_cmd = "^2.0"
predicates = "0.9"
sys-info = "0.7.0"